version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - gradle clean build

artifacts:
  files:
    - build/libs/application.jar
  discard-paths: yes